spring:
  data:
    mongodb:
     uri: mongodb://localhost:27017/love-agent-memory
  ai:
    chat:
      memory:
        repository:
          mongodb:  # 这里必须是 mongodb，不是 mongo！
            collection-name: love-agent-memory  # 你的自定义集合名
    dashscope:
      api-key: ${ALIBABA_API_KEY}
      chat:
        options:
          model: qwen-plus
          temperature: 0.8
#          multi-model: true
#          enable-search: true
#          search-strategy: agent
# springdoc-openapi ??????
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.love.loveagentxyc.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
server:
  port: 8123
  servlet:
      context-path: /api
